version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: dist

